# Generated by Django 5.1.7 on 2025-04-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_districts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemap',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
    ]
