# Generated by Django 5.1.7 on 2025-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_districts', '0002_statemap_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemap',
            name='coords',
            field=models.TextField(default=''),
        ),
    ]
