# Generated by Django 5.1.7 on 2025-04-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_districts', '0003_statemap_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemap',
            name='map',
            field=models.JSONField(default={}),
        ),
    ]
