# Generated by Django 5.1.7 on 2025-04-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_districts', '0004_statemap_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statemap',
            name='coords',
        ),
        migrations.AlterField(
            model_name='statemap',
            name='map',
            field=models.JSONField(default=dict),
        ),
    ]
