# Generated by Django 5.1.7 on 2025-05-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_districts', '0005_remove_statemap_coords_alter_statemap_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=2)),
                ('school_district', models.CharField(default='', max_length=40)),
                ('total_pop', models.IntegerField(default=0)),
                ('poverty_pop', models.IntegerField(default=0)),
            ],
        ),
    ]
